### ISSUE TITLE
Bug : 메인 페이지에서 코디 등록 여러 번 가능 한 것 

### ISSUE THREAD

**Issue by bigyou98** [potato-club/temperature-outfit#107]
# Bug : 메인 페이지에서 코디 등록 여러 번 가능 한 것 
- 1번만 되야 한다.

### 서버에서 막을지?
    - 서버에서 이미 등록된 것이 있다면 막는다.
### 프론트에서 막을지?
    - 오늘 날짜에 등록되어있는지 확인하기 위해 등록되어있는 코디들을 GET API를 호출 해서 오늘 날짜가 있는지 확인해야함
 
- 그 이후 행동
      - 모달 창으로 이미 등록되어있는게 있다고 할지?
      - 이미 등록되어있는 코디페이지로 가게 할지?

**Comment by bigyou98** [comment]
![image](https://user-images.githubusercontent.com/76721795/198877304-bc40e4e5-68bc-4e59-bae4-3e47225bc872.png)

**Comment by pdom0327** [comment]
등록 페이지 접속 자체를 서버에서 막을 수는 없기 때문에 둘다 막아야 한다고 생각합니다.

**Comment by bigyou98** [comment]
![image](https://user-images.githubusercontent.com/76721795/200573406-01714d83-a4b9-47ba-a4b5-17113f2389fb.png)
