### ISSUE TITLE
Feat : 달력 month기준으로 API 호출

### ISSUE THREAD

**Issue by bigyou98** [potato-club/temperature-outfit#55]
## 할일
- 오늘을 기준으로 month를 알아내야함
- 버튼 클릭으로 달력 month 변환시 해당 month를 기준으로 API를 호출해야 함

**Comment by bigyou98** [comment]
![image](https://user-images.githubusercontent.com/76721795/184873580-b4595381-5c28-469f-a028-d6c35770f0f6.png)
왼쪽 버튼 관련된 함수를 라이브러리에서 찾아야 한다.
- 버튼 클릭 시 달(month)가 바뀌는데 해당 버튼 클릭했을 때 그 달의 따라서 API를 호출하기 위함

**Comment by bigyou98** [comment]
![image](https://user-images.githubusercontent.com/76721795/184874659-c790c0d8-e494-4a90-9a45-9024e8a97607.png)
8월 1 ~26일까지 호출하는데

![image](https://user-images.githubusercontent.com/76721795/184874573-06225632-a70e-425f-b1c0-d7dfca522980.png)

호출하지 않은 7월 1일도 값이 들어옴

@pdom0327 서버에서 필터링이 되지 않는듯함

**Comment by pdom0327** [comment]
![image](https://user-images.githubusercontent.com/12953393/184906453-f939cca3-3538-417b-b32a-c64ab6b42738.png)
테스트해보니 `startDate`, `endDate`는 작동하고 오히려 `minRating`, `maxRating`에 값이 있으면 서버에서 타입 처리 안 되어있어서 오류가 납니다.

값이 제대로 넘어오지 않고 있는 거 같아요.
