### ISSUE TITLE
8월 22일 회의 주제

### ISSUE THREAD

**Issue by bigyou98** [potato-club/temperature-outfit#65]
### 1. 지역 불러오는 API의 id값이 의미없는 number [해결]
![image](https://user-images.githubusercontent.com/76721795/185141422-2ad45814-116c-4f42-b8e4-235f69ba8267.png)
![image](https://user-images.githubusercontent.com/76721795/185141474-4ec27ba0-904f-4a6b-889f-2e9deb4d567a.png)
### 2. 기후를 icon으로 표시 할 때 기후 관련 data는 어떻게 할 것인지 [해결]
  - main화면의 3D 모델 아이콘도 어떻게 할 것인지 같이 논의
  
### 지원 해줌
![image](https://user-images.githubusercontent.com/76721795/185911963-9f0a5aa5-f849-4e5a-be07-ce04e6262470.png)

**Comment by bigyou98** [comment]
1 해결

**Comment by KoJaem** [comment]
@bigyou98 태그 알람 테스트

**Comment by bigyou98** [comment]
https://www.notion.so/8-22-ae851c04de3f4e5c8a9d388d3aa724ea
